// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrMAIWKAFtVZPeZxpFOA5XIwGtJG0Rap4',
    appId: '1:970511730061:web:83dbb384012899ed5e29c4',
    messagingSenderId: '970511730061',
    projectId: 'mobiletodo',
    authDomain: 'mobiletodo.firebaseapp.com',
    storageBucket: 'mobiletodo.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAW1QbCYfqgyP0vlXUMXXQMWwAtD64ilIU',
    appId: '1:970511730061:android:4fbfff7d41f4a9cd5e29c4',
    messagingSenderId: '970511730061',
    projectId: 'mobiletodo',
    storageBucket: 'mobiletodo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmBucnvx9Jk146YX4ltclKY3aLkmHlbg4',
    appId: '1:970511730061:ios:27fc8acabf4be8975e29c4',
    messagingSenderId: '970511730061',
    projectId: 'mobiletodo',
    storageBucket: 'mobiletodo.appspot.com',
    iosClientId:
        '970511730061-169iejqhs6i95ukhi34o8tkk73fqnll8.apps.googleusercontent.com',
    iosBundleId: 'com.pengodigital.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmBucnvx9Jk146YX4ltclKY3aLkmHlbg4',
    appId: '1:970511730061:ios:27fc8acabf4be8975e29c4',
    messagingSenderId: '970511730061',
    projectId: 'mobiletodo',
    storageBucket: 'mobiletodo.appspot.com',
    iosClientId:
        '970511730061-169iejqhs6i95ukhi34o8tkk73fqnll8.apps.googleusercontent.com',
    iosBundleId: 'com.pengodigital.todo',
  );
}
